name: main
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  build-static-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7
    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: 1.22.7
    - name: Build
      run: make build
    - name: FMT
      run: make fmt
    - name: VET
      run: make vet
    - name: LINT
      run: make lint
      env:
        LINT: true
  build-ut:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7
    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: 1.22.7
    - name: ut
      run: make test
      env:
        UT: true
  FV:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7
    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: 1.22.7
    - name: fv
      run: make create-cluster fv
      env:
        FV: true